config/routes.rb
Reppio::Application.routes.draw do
  resources :groups
  controller :groups do
    get "join" => :join_group, :as => :join_group
    get "request_join" => :request_join_group, :as => :request_join_group
    get "leave" => :leave_group, :as => :leave_group
    get "remove_from_group" => :remove_from_group, :as => :remove_from_group
    get "handle_request" => :handle_request_join_group, :as => :handle_request
    get "/groups/:id/invite_to_group" => :invite_to_group, :as => :invite_to_group
    post "/groups/send_email_to_invite_to_group" => :send_email_to_invite_to_group
    post "invite_facebook_connections_to_group" => :invite_facebook_connections_to_group
    get "notifications" => :notifications, :as => :groups_notifications
    get "join_autogroup_modal" => :join_autogroup_modal, :as => :join_autogroup_modal
  end

  controller :payments do
    match "submit_deposit" => :submit_deposit, :as => :submit_deposit
    match "buy" => :buy, :as => :buy
    match "do_deposit" => :do_express_checkout_payment_for_deposit, :as => :do_express_checkout_payment_for_deposit
    match "payments/ipn_notification/:id/" => :ipn_notification, :as => :ipn_notification
    get "payments/canceled_payment_request" => :canceled_payment_request, :as => :canceled_payment
    get "payments/completed_payment_request/:id/" => :completed_payment_request, :as => :completed_payment
    get "payments/failed_payment" => :failed_payment, :as => :failed_payment
    post "request_payment" => :request_payment, :as => :request_payment
    match "cancel_request_payment" => :cancel_request_payment, :as => :cancel_request_payment
  end

  controller :manage do
    get "manage/selling" => :selling, :as => :manage_selling
    get "manage/buying" => :buying, :as => :manage_buying
    get "manage/completed_buying" => :completed_buying, :as => :manage_completed_buying
    get "manage/completed_selling" => :completed_selling, :as => :manage_completed_selling
    get "manage/drafts_selling" => :drafts_selling, :as => :manage_drafts_selling

    get "manage/selling/:id" => :selling_posting_conversations, :as => :selling_posting_conversations
    get "manage/buying/:id" => :buying_posting_conversation, :as => :buying_posting_conversation
    get "manage/completed_selling/:id" => :completed_selling_posting_conversations, :as => :completed_selling_posting_conversations
    get "manage/completed_buying/:id" => :completed_buying_posting_conversation, :as => :completed_buying_posting_conversation
    get "manage/drafts_selling/:id" => :drafts_selling_redirect

    get "manage/selling/:id/:buyer_id" => :selling_posting_conversation, :as => :selling_posting_conversation
    get "manage/completed_selling/:id/:buyer_id" => :completed_selling_posting_conversation, :as => :completed_selling_posting_conversation

    match "manage" => redirect("/manage/selling"), :as => :manage

    get "repscore" => :repscore, :as => :repscore

    get "manage/reviews" => :reviews

    match "manage/add_student_email" => :add_student_email
    match "manage/rep_center_references" => :rep_center_references, :as => :rep_center_references
    match "manage/rep_center_referrals" => :rep_center_referrals, :as => :rep_center_referrals
    match "rep_center" => redirect("/manage/reviews"), :as => :rep_center
    match "verifications" => :verifications, :as => :verifications
    match "reputation_explained" => :reputation_explained, :as => :reputation_explained

    get "manage/interests" => :interests, :as => :interests
    match "toggle_interest" => :toggle_interest, :as => :toggle_interest

    get "conversations" => :redirect_to_conversation
    get "conversations/:id" => :redirect_to_conversation

  end

  controller :watchlist do
    match "watchlist/bookmarks" => :bookmarks
    match "watchlist/alert" => :alert, :as => :search_alert
    match "watchlist" => redirect("/watchlist/bookmarks"), :as => :watchlist
  end

  controller :bookmarks do
    post "bookmarks" => :toggle
    match "bookmarks/:posting_id" => :toggle
  end


  resources :alerts, :only => [:create, :edit, :destroy, :update]

  controller :static do
    match "about" => :about
    match "jobs" => :jobs
    match "faq" => :faq
    match "terms" => :terms
    match "privacy" => :privacy
    match "team" => :team
    match "press" => :press
    match "app" => :app
    get "contact" => :contact
    post "contact" => :contactSend
  end


  resources :references
  controller :references do
    match "contacts/:importer/callback" => :invite
    match "contacts/failure" => :failure
    post "references/send_invites_list" => :send_invites_list
    post "references/send_references_given_email_list" => :send_references_given_email_list
    post "accept_or_reject_references" => :accept_or_reject_references, :as => :accept_or_reject_references

  end

  post 'flag', :to => 'flags#create', :as => :flag

  controller :reviews do
    get "reviews" => :index, :as => :my_reviews
    post "reviews/vote" => :vote, :as => :review_vote
    post "reviews" => :create
    match "reviews/:id" => :respond, :as => :respond_to_review
  end

  controller :browse do
    match "search" => :show, :as => :search
    match "search_json" => :autocomplete
    match "load_mini_map", :load_mini_map, :as => :load_mini_map
  end

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "login" => :destroy
    get "jackterminal" => :jack_signin
    post "jackterminal" => :jack_create
    get "interstitial" => :interstitial, :as => :interstitial
    match "interstitial/*redirect" => :interstitial, :as => :interstitial
    match "logout" => :destroy, :as => :logout
    match 'auth/facebook/callback' => :create_auth
    match 'auth/twitter/callback' => :twitter
    match 'auth/linkedin/callback' => :linkedin
    match 'auth/failure' => :failure
  end

  controller :mobile do
    match "mobile/posting/categorize2" => :mobile_posting_categorize2
    match "mobile/posting/create2" => :mobile_posting_create2
    match "mobile/toggle/push" => :mobile_toggle_push
    match "mobile/group/info" => :group_info

    get "mobile/app/version" => :mobile_app_version
    match "mobile/auth/:provider/callback" => :mobile_create_auth
    match "mobile/login" => :mobile_create
    match "mobile/profile/update" => :mobile_profile_update
    match "mobile/profile/get" => :mobile_profile_get
    match "mobile/posting/categorize" => :mobile_posting_categorize
    match "mobile/posting/create" => :mobile_posting_create
    match "mobile/posting/get" => :mobile_posting_get
    match "mobile/posting/update" => :mobile_posting_update
    match "mobile/fields/get" => :mobile_fields_get
    match "mobile/fields/get2" => :mobile_fields_get2
    match "mobile/manager/get" => :mobile_manager_get
    match "mobile/messages/get" => :mobile_messages_get
    match "mobile/conversation/create" => :mobile_conversation_create
    match "mobile/conversations/get" => :mobile_conversations_get
    #match "mobile/manager/buying"=>:mobile_manager_buying
    #match "mobile/manager/selling"=>:mobile_manager_selling
    match "mobile/conversation/update" => :mobile_conversation_update
    match "mobile/email/signup" => :mobile_email_signup
    match "mobile/categories/all" => :mobile_categories_all
    match "mobile/alert/create" => :mobile_alert_create
    match "mobile/alert/remove" => :mobile_alert_remove
	match "mobile/alert/edit" => :mobile_alert_edit
	
    match "mobile/transaction/complete" => :mobile_transaction_complete
    match "mobile/transaction/cc" => :mobile_transaction_cc

    match "mobile/push/setup" => :mobile_push_setup
    match "mobile/push/setup/android" => :mobile_push_setup_android
    #TODO remove after testing
    match "mobile/push/send/android" => :mobile_push_send_android
    match "mobile/push/conversation/get" => :mobile_push_conversation_get

    match "mobile/posting/agree/sell" => :mobile_posting_agree_sell
    match "mobile/posting/cancel/sell" => :mobile_posting_cancel_sell

    match "mobile/payments/transact/cc" => :mobile_payments_transact_cc
    match "mobile/payments/set/seller" => :mobile_payments_set_seller
    match "mobile/payments/set/buyer" => :mobile_payments_set_buyer
    match "mobile/payments/get/cards" => :mobile_payments_get_cards
    match "mobile/payments/get/card" => :mobile_payments_get_card
    match "mobile/payments/update/card" => :mobile_payments_update_card
    match "mobile/payments/invalidate/card" => :mobile_payments_invalidate_card

    match "mobile/payments/get/bankAccounts" => :mobile_payments_get_bankAccounts
    match "mobile/payments/get/bankAccount" => :mobile_payments_get_bankAccount
    match "mobile/payments/delete/bankAccount" => :mobile_payments_delete_bankAccount

    match "mobile/browse" => :browse
    match "mobile/search" => :search
    match "mobile/listing_details_view" => :listing_details_view

    match "mobile/return_groups" => :return_groups

    match "mobile/toggle_bookmark" => :toggle_bookmark
    match "mobile/return_bookmarks" => :return_bookmarks


    match "mobile/join_group" => :join_group
    match "mobile/leave_group" => :leave_group

    match "mobile/onboarding_add_interests" => :onboarding_add_interests
    match "mobile/onboarding_add_school_email" => :onboarding_add_school_email


    match "mobile/reset_password" => :reset_password
	
	match "mobile/get_alerts"=>:get_alert_labels
	match "mobile/get_alert_postings"=>:get_alert_postings
	
	match "mobile/queue_cg"=>:queue_craigslist_post
  end


  controller :upload do
    get ":user_name/upload" => :catchGet #Not sure why; simply setting a form :url => handle_upload_url (as in fileupload/_main) will cause a get call to said URL. Catch it and return nothing to avoid an annoying (but harmless?) routing error.
    post ":user_name/upload" => :create, :as => :handle_upload
    delete ":user_name/postings/upload_destroy/:id" => :destroy, :as => :upload_destroy
  end


  scope ":user_name", :as => "user" do

app/models/group.rb
class Group < ActiveRecord::Base
  def to_param
    short_name
  end

  has_and_belongs_to_many :users
  has_one :owner, :class_name => 'User', :foreign_key => "owner_id"

  has_and_belongs_to_many :postings
  zip_code_regex=/\d{5}/
  validates :long_name, :length => {:in => 3..50}, :uniqueness => {:case_sensitive => false}
  validates :short_name, :length => {:in => 1..20}, :uniqueness => {:case_sensitive => false}
  validates :zip_code, :format => {:with => zip_code_regex, :message => "must be 5 digits"}

  geocoded_by :zip_code
  after_validation :geocode, :if=>:zip_code_changed?
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_header_column(label, params_name, current_order)
    if current_order==params_name
      "<th>#{label} &blacktriangledown;</th>".html_safe
    else
      "<th>#{link_to(label, groups_path(:order=>params_name))}</th>".html_safe
    end
  end
end

app/views/groups/_form.html.erb
<div id="groups-form">
<div style="margin-right:45px;">
    <h3 style="margin-top:0px;"><%= new_or_edit=="new" ? "Create a New Group" : "Edit Group: #{@group.long_name}" %></h3>
    You can create a group to bring together people with common interests, locations, or organizations. A group can be open to the public or require approval to join. Invite your friends and easily find out what they're selling!
    <hr>
</div>

<%= form_for @group, :validate => true do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div style="padding:20px; background:#f6f6f6; width:455px;">
    <div class="control-group">
      <%= f.label("Group Name", :class => "control-label") %>
      <div class="controls">
        <%= f.text_field :long_name, :maxlength => '50', :style=>"width:60%;", :placeholder=>"e.g. Hyde Park Pickup Basketball League"%>
      </div>
    </div>

    <div class="control-group">
      <%= f.label(:short_name, :class => "control-label") %>
      <div class="controls">
        <%= f.text_field :short_name, :maxlength => '20', :style=>"width:60%;", :id=>"short-name", :placeholder => "e.g. hpa" %>
      </div>
    </div>
    <div style="width:300px; background:#DDD; padding:5px 10px 5px 10px"><b>Your Reppio Group Website URL:</b>  http://www.reppio.com/groups/<span id="short-name-url"></span></div>
   </div>
     <br>

    <div class="control-group">
      <%= f.label("People that want to join this group", :class => "control-label") %>
      <div class="controls">
        <%= f.radio_button :may_join_without_admin_approval, false %>
        <label for="may_join_without_admin_approval_false" style="display:inline-block;">&nbsp;must be approved by the group owner &nbsp;&nbsp;&nbsp;&nbsp;</label>
       <%= f.radio_button :may_join_without_admin_approval, true %>
        <label for="may_join_without_admin_approval_true" style="display:inline-block;"> &nbsp;can join without approval</label>
      </div>
    </div>

      <div class="control-group">
        <%= f.label(:zip_code, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field :zip_code, :maxlength => '5', :style=>"width:80px;"%>
        </div>
      </div>
    <div class="control-group">
      <%= f.label("Group Website", :class => "control-label") %>
      <div class="controls">
        <%= f.text_field :external_url, :style=>"width:60%;", :placeholder=>"link to your group's website (optional)" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label("Picture URL", :class => "control-label") %>
      <div class="controls">
        <%= f.text_field :picture_url, :style=>"width:60%;", :placeholder=>"URL to your group's picture (optional)" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label(:description, :class => "control-label") %>
      <div class="controls">
        <%= f.text_area :description, :style=>"width:60%; height:100px;",  :placeholder => "description (optional)" %>
      </div>
    </div>


  <div class="actions">
    <%= f.submit "#{new_or_edit=="new" ? "Create" : "Edit"} Group", :class=>"rep-btn rep-btn-orange" %>
  </div>
<% end %>
</div>

app/views/groups/_join_autogroup_modal.html.erb
<div id="joinGroupModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="joinGroupModalLabel" aria-hidden="true">
  <div class="modal-header">
    <h4 style="margin-top:0;">Join <%= group.long_name %></h4>
    <button type="button" class="x-button" data-dismiss="modal" aria-hidden="true"><span class="x">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <%= form_for current_user, :url => add_autogroup_email_url, :html => {:multipart => true, :class => "form-horizontal"}, :remote => true do |f| %>
        <% pending_email=EmailAddress.where("user_id=? AND is_primary=false AND email_confirmed =false", current_user.id)
           if pending_email.blank?
             current_user.email_addresses.build %>
            <p> Please enter your <%= group.email_extension %> email address. </p>
            <input id="user_email_addresses_attributes_<%= current_user.email_addresses.length-1 %>_email" name="user[email_addresses_attributes][<%= current_user.email_addresses.length-1 %>][email]" size="30" type="text">
            <br><br>
            <%= submit_tag "Join", :class => "rep-btn rep-btn-orange" %>

        <% else %>
            You already have an email that needs verification. Please check your email
            at <%= pending_email[0].email %> to verify the address.<br><br>
            <%= link_to "Resend confirmation email", send_confirmation_secondary_email_url %>
            · <%= link_to "Cancel", cancel_secondary_email_confirmation_url %>
        <% end %>

    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<% title "Reppio: Edit Group" %>
<% content_for :activeManageMenu, "groups" %>
<% content_for :activeManageSubMenu, params[:id] %>
<% content_for :center_content do %>
    <%= render(:partial=>'form', :locals=>{:new_or_edit=>"edit"}) %>

<% end %>

<%= render :template => "manage/manage" %>

app/views/groups/index.html.erb
<% title "Reppio: All Groups" %>
<% content_for :activeManageMenu, "groups" %>
<% content_for :activeManageSubMenu, "browse_groups" %>
<% content_for :center_content do %>

    <h3>Groups near you</h3>
      <table class="table striped" style="width:700px;">
        <thead>
        <%= group_header_column("Name", "name", params[:order])  %>
        <%= group_header_column("Distance", "distance", params[:order])  %>
        <%= group_header_column("Members", "count", params[:order])  %>
        </thead>
        <tbody>
        <%degToR = Math::PI / 180
          @groups.each do |group| %>
            <tr>
              <td><%= link_to group.long_name, group %></td>
              <td><%= ::DistanceCalculations.distance_between(current_user.latitude*degToR,current_user.longitude*degToR, group.latitude*degToR, group.longitude*degToR).round(1)%> mi</td>
              <td><%= pluralize(group.members_count, "member") %></td>

              <td><% if group.may_join_without_admin_approval && group.email_extension.blank? %><i class="icon-globe"></i><% end %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br/>

<% end %>

<%= render :template => "manage/manage" %>

app/views/groups/invite_to_group.html.erb
<% title "Invite people to join #{@group.long_name}" %>
<% content_for :activeManageMenu, "groups" %>
<% content_for :center_content do %>
      <h1>Invite people to join <%= @group.long_name %></h1>
     <%= link_to image_tag("social_icons/facebook.png"), "http://www.facebook.com/sharer.php?u=http://www.reppio.com/groups/#{@group.short_name}", :target=>"_blank" %>
    <%= link_to image_tag("social_icons/twitter.png"), "https://twitter.com/share?url=http://www.reppio.com/groups/#{@group.short_name}&text=#{url_encode("Join my group on @reppio")}", :target=>"_blank" %>

    <% if @fb_ids && !@fb_ids.blank? %>
          <%= form_tag({:action => :invite_facebook_connections_to_group, :controller => :groups}, :method => "post") %>
          <%= hidden_field_tag :group_id, @group.id  %>
          <h3>Friends on Reppio</h3>
          <% @fb_ids.each_with_index do |fb_id, index|
            friend=User.find_by_facebook_id(fb_id) %>
            <div class="image-checkbox">
             <%= check_box_tag "user_ids[]", friend.id, false, :id=>"friend#{index}" %>
              <label class="checkbox" for="friend<%=index%>">
               <%= profile_pic_if_exists(size="thumb", friend) %>
              <br><br> <%= friend.first_name %>
              </label>
            </div>
           <% end %>
          <p><%= submit_tag "Invite", :class => "btn btn-primary" %></p>
          </form>
      <% end %>

     <br><br>
    <h3>Email</h3>
        <%= form_tag({:action => :send_email_to_invite_to_group, :controller => :groups}, :method => "post") %>
        <%= hidden_field_tag :group_id, @group.id  %>
        <br>

        <p><%= text_area_tag 'emails', nil, :rows => 3, :cols => 50, :placeholder => "jack@reppio.com, samir@gmail.com, ...", :style => "width:90%" %></p>

        <p>Personal Message
          (optional)<br><%= text_area_tag 'personal_message', nil, :rows => 4, :cols => 50, :style => "width:90%", :placeholder => "Join me on \"#{@group.long_name}\" group on Reppio, so that we can give each other first dibs or share our stuff." %>
        </p>

        <p><%= submit_tag "Invite", :class => "btn btn-primary" %></p>
        </form>

<% end %>

<%= render :template => "manage/manage" %>

app/views/groups/join_autogroup_modal.js.erb
$("<%= escape_javascript(render(:partial => "groups/join_autogroup_modal", :locals => {:group => @group})) %>").modal('show').on('hidden', function () {
    $(this).remove();
});

app/views/groups/new.html.erb
<% title "Reppio: New Group" %>
<% content_for :activeManageMenu, "groups" %>
<% content_for :activeManageSubMenu, "new_groups" %>
<% content_for :center_content do %>

    <%= render(:partial=>'form', :locals=>{:new_or_edit=>"new"}) %>

<% end %>

<%= render :template => "manage/manage" %>

app/views/groups/notifications.html.erb
<% title "Reppio: All Groups" %>
<% content_for :activeManageMenu, "groups" %>
<% content_for :activeManageSubMenu, "notification_groups" %>
<% content_for :center_content do %>

    <h3>Pending notifications</h3>
    <p>Group owners may find notifications for activity within their groups here.</p>

    <% group_requests=GroupRequest.find_all_by_owner_id(current_user.id)
       if !group_requests.blank? %>

        <% group_requests.each do |group_request|
          user_that_wants_to_join=User.find(group_request.user_id)
          group=Group.find(group_request.group_id) %>
            <%= link_to user_that_wants_to_join.first_name, user_that_wants_to_join %> wants to join
            <%= link_to group.long_name, group %>
            <%= link_to "Approve Request", handle_request_url(:id => group_request, :status => "accept"), :class => "btn btn-success" %>
            <%= link_to "Ignore Request", handle_request_url(:id => group_request, :status => "ignore"), :class => "btn btn-danger" %>

        <% end
           end%>

<% end %>

<%= render :template => "manage/manage" %>

app/views/groups/remove_from_group.js.erb
$('#member<%= @user_to_be_removed.id%>').remove();

app/views/groups/show.html.erb
<style>
    .active {
        margin-left: 10px;
    }
</style>

<% title "Reppio: #{@group.long_name}" %>
<% content_for :activeManageMenu, "groups" %>
<% content_for :center_content do %>
    <% is_group_owner = (signed_in? && current_user.id==@group.owner_id)
       is_member = !@members.where("id=?", current_user.id).blank?
    %>
    <% @members.sample(10).each do |member| %>
        <%= link_to profile_pic_if_exists("thumb", member), member, :class=>"hasTooltip", :title=>member.first_name %>
    <% end %>


    <ul class="nav nav-tabs" style="margin-top:10px;width:730px;">
      <li class="active">
        <a href="#home" data-toggle="tab"><%= @group.long_name %></a>
      </li>
      <li><a href="#about" data-toggle="tab">About</a></li>
      <% if signed_in? %>
          <% if is_member %>
              <li><%= link_to "Invite others", invite_to_group_url(@group) %></li>
          <% end %>
          <% if is_group_owner %>
              <li><a href="#edit" data-toggle="tab">Edit Group</a></li>
              <% if !@group.may_join_without_admin_approval %>
                  <li><a href="#edit-members" data-toggle="tab">Edit Members</a></li>
              <% end %>
          <% elsif is_member # you cannot leave an auto-group, MUAHHAHAHAHA
               show_leave=true
          %>
          <% elsif not (group_request=GroupRequest.where("user_id=? AND group_id=?", current_user.id, @group.id)).blank? %>
              <li>
                <div style="padding:5px 10px 5px 10px; background-color:#f6f6f6;margin-left:20px;"><em>Requested to join
                  <%= time_ago_in_words(group_request[0].created_at) %> ago.</em></div>
              </li>
          <% elsif @group.may_join_without_admin_approval %>
              <% if @group.email_extension.blank? %>
                  <li><%= link_to "Join #{@group.long_name}", join_group_url(:id => @group) %></li>
              <% elsif !@group.email_extension.blank? && !is_member %>
                  <li><%= link_to "Join #{@group.long_name}", join_autogroup_modal_url(:id => @group), :remote => true %></li>
              <% end %>
          <% else %>
              <li><%= link_to "Join #{@group.long_name}", request_join_group_url(:id => @group) %></li>
          <% end %>
          <% if is_member %>
              <li class="dropdown pull-right">
                <a class="dropdown-toggle" id="group-drop" role="button" data-toggle="dropdown" href="#group-dropdown"><i class="icon-cog"></i>
                  <b class="caret"></b></a>
                <ul id="menu3" class="dropdown-menu" role="menu" aria-labelledby="group-drop" style="margin-top:0px; border-radius:0px; margin-right:1px;">
                  <li><%= link_to "Invite others", invite_to_group_url(@group) %></li>
                  <% if is_group_owner %>
                      <li><%= link_to 'Edit', edit_group_path(@group) %> </li>
                      <li class="divider"></li>
                      <li><%= link_to 'Destroy', @group, confirm: 'Are you sure you want to delete this group?', method: :delete %></li>
                  <% elsif show_leave %>
                      <li class="divider"></li>
                      <li><%= link_to "Leave #{@group.long_name}", leave_group_url(:id => @group) %></li>
                  <% end %>
                </ul>

          <% end
             end %>
      </li>
    </ul>


    <div class="tab-content" style="width:730px; padding:10px;">
      <div class="tab-pane active" id="home">

        <% if is_group_owner %>
            <div>
              You are an administrator for <%= @group.long_name %>. Use your power for good, not evil!
              <br><br>

              <h3>Pending notifications</h3>

              <p>
                <% group_requests=GroupRequest.find_all_by_owner_id_and_group_id(current_user.id, @group.id).each do |group_request|
                  user_that_wants_to_join=User.find(group_request.user_id) %>
                    <%= link_to user_that_wants_to_join.first_name, user_that_wants_to_join %>
                    <%= link_to "Approve Request", handle_request_url(:id => group_request, :status => "accept"), :class => "btn btn-success" %>
                    <%= link_to "Ignore Request", handle_request_url(:id => group_request, :status => "ignore"), :class => "btn btn-danger" %>
                    <br>
                <% end %>
                <%= "You have no pending notifications." if group_requests.blank? %>
              </p>
            </div>
        <% end %>

        <div id="list-of-group-postings">
          <% if is_member || (@group.may_join_without_admin_approval && @group.email_extension.blank?)  %>
              <span class="search-within-group">
                Search within <%= @group.long_name %> group. <%=  link_to "click here", search_url(:group=>@group.id) %>
              </span>

              <h3>Newest Listings</h3>
              <% @group_postings.each do |posting| %>
                  <%= render(:partial => "postings/pic_and_price_square", :locals => {:posting => posting, :seller_name => User.find(posting.user_id).user_name}) %>
              <% end %>


              <%= will_paginate @group_postings %>
              <%= "No one in this group has posted anything." if @group_postings.blank? %>
          <% else %>
              This is a private group. You must be a member to see the postings in this group.
          <% end %>
        </div>
      </div>
      <div class="tab-pane" id="about">

        <% if @group.picture_url != "" %>
            <p>
              <%= image_tag @group.picture_url %>
            </p>
        <% end %>

        <% if not @group.external_url.blank? %>
            <p>
              <b>Website:</b> <%= @group.external_url %>
            </p>
        <% end %>

        <% if current_user.latitude %>
            <p>
              <% degToR = Math::PI / 180 %>
              <b>Distance: </b>About <%= ::DistanceCalculations.distance_between(current_user.latitude*degToR, current_user.longitude*degToR, @group.latitude*degToR, @group.longitude*degToR).round(1) %>
              miles away
            </p>
        <% end %>

        <p><%= simple_format h(@group.description) %> </p>
      </div>


      <div class="tab-pane" id="edit">
        <%= render(:partial => 'form', :locals => {:new_or_edit => "edit"}) %>
      </div>
      <% if is_group_owner && !@group.may_join_without_admin_approval %>
          <div class="tab-pane" id="edit-members">
            <table class="table striped" style="width:700px;">
              <% (@members.reject { |member| member.id==@group.owner_id }).each do |member| %>
                  <tr id="member<%= member.id %>">
                    <td><%= "#{member.first_name} #{member.last_name}" %></td>
                    <td><%= link_to "x", remove_from_group_url(:id => @group.short_name, :user_id => member.id), :confirm => "Are you sure you want to remove #{member.first_name}?", :remote => true %></td>
                  </tr>
              <% end %>
            </table>
          </div>
      <% end %>

    </div>








<% end %>

<%= render :template => "manage/manage" %>