config/routes.rb
    match "privacy" => :privacy
    match "team" => :team
    match "press" => :press
    match "app" => :app
    get "contact" => :contact
    post "contact" => :contactSend
  end


  resources :references
  controller :references do
    match "contacts/:importer/callback" => :invite
    match "contacts/failure" => :failure
    post "references/send_invites_list" => :send_invites_list
    post "references/send_references_given_email_list" => :send_references_given_email_list
    post "accept_or_reject_references" => :accept_or_reject_references, :as => :accept_or_reject_references

  end

  post 'flag', :to => 'flags#create', :as => :flag

  controller :reviews do
    get "reviews" => :index, :as => :my_reviews
    post "reviews/vote" => :vote, :as => :review_vote
    post "reviews" => :create
    match "reviews/:id" => :respond, :as => :respond_to_review
  end

  controller :browse do
    match "search" => :show, :as => :search
    match "search_json" => :autocomplete
    match "load_mini_map", :load_mini_map, :as => :load_mini_map
  end

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "login" => :destroy
    get "jackterminal" => :jack_signin
    post "jackterminal" => :jack_create
    get "interstitial" => :interstitial, :as => :interstitial
    match "interstitial/*redirect" => :interstitial, :as => :interstitial
    match "logout" => :destroy, :as => :logout
    match 'auth/facebook/callback' => :create_auth
    match 'auth/twitter/callback' => :twitter
    match 'auth/linkedin/callback' => :linkedin
    match 'auth/failure' => :failure
  end

  controller :mobile do
    match "mobile/posting/categorize2" => :mobile_posting_categorize2
    match "mobile/posting/create2" => :mobile_posting_create2
    match "mobile/toggle/push" => :mobile_toggle_push
    match "mobile/group/info" => :group_info

    get "mobile/app/version" => :mobile_app_version
    match "mobile/auth/:provider/callback" => :mobile_create_auth
    match "mobile/login" => :mobile_create
    match "mobile/profile/update" => :mobile_profile_update
    match "mobile/profile/get" => :mobile_profile_get
    match "mobile/posting/categorize" => :mobile_posting_categorize
    match "mobile/posting/create" => :mobile_posting_create
    match "mobile/posting/get" => :mobile_posting_get
    match "mobile/posting/update" => :mobile_posting_update
    match "mobile/fields/get" => :mobile_fields_get
    match "mobile/fields/get2" => :mobile_fields_get2
    match "mobile/manager/get" => :mobile_manager_get
    match "mobile/messages/get" => :mobile_messages_get
    match "mobile/conversation/create" => :mobile_conversation_create
    match "mobile/conversations/get" => :mobile_conversations_get
    #match "mobile/manager/buying"=>:mobile_manager_buying
    #match "mobile/manager/selling"=>:mobile_manager_selling
    match "mobile/conversation/update" => :mobile_conversation_update
    match "mobile/email/signup" => :mobile_email_signup
    match "mobile/categories/all" => :mobile_categories_all
    match "mobile/alert/create" => :mobile_alert_create
    match "mobile/alert/remove" => :mobile_alert_remove
	match "mobile/alert/edit" => :mobile_alert_edit
	
    match "mobile/transaction/complete" => :mobile_transaction_complete
    match "mobile/transaction/cc" => :mobile_transaction_cc

    match "mobile/push/setup" => :mobile_push_setup
    match "mobile/push/setup/android" => :mobile_push_setup_android
    #TODO remove after testing
    match "mobile/push/send/android" => :mobile_push_send_android
    match "mobile/push/conversation/get" => :mobile_push_conversation_get

    match "mobile/posting/agree/sell" => :mobile_posting_agree_sell
    match "mobile/posting/cancel/sell" => :mobile_posting_cancel_sell

    match "mobile/payments/transact/cc" => :mobile_payments_transact_cc
    match "mobile/payments/set/seller" => :mobile_payments_set_seller
    match "mobile/payments/set/buyer" => :mobile_payments_set_buyer
    match "mobile/payments/get/cards" => :mobile_payments_get_cards
    match "mobile/payments/get/card" => :mobile_payments_get_card
    match "mobile/payments/update/card" => :mobile_payments_update_card
    match "mobile/payments/invalidate/card" => :mobile_payments_invalidate_card

    match "mobile/payments/get/bankAccounts" => :mobile_payments_get_bankAccounts
    match "mobile/payments/get/bankAccount" => :mobile_payments_get_bankAccount
    match "mobile/payments/delete/bankAccount" => :mobile_payments_delete_bankAccount

    match "mobile/browse" => :browse
    match "mobile/search" => :search
    match "mobile/listing_details_view" => :listing_details_view

    match "mobile/return_groups" => :return_groups

    match "mobile/toggle_bookmark" => :toggle_bookmark
    match "mobile/return_bookmarks" => :return_bookmarks


    match "mobile/join_group" => :join_group
    match "mobile/leave_group" => :leave_group

    match "mobile/onboarding_add_interests" => :onboarding_add_interests
    match "mobile/onboarding_add_school_email" => :onboarding_add_school_email


    match "mobile/reset_password" => :reset_password
	
	match "mobile/get_alerts"=>:get_alert_labels
	match "mobile/get_alert_postings"=>:get_alert_postings
	
	match "mobile/queue_cg"=>:queue_craigslist_post
  end


  controller :upload do
    get ":user_name/upload" => :catchGet #Not sure why; simply setting a form :url => handle_upload_url (as in fileupload/_main) will cause a get call to said URL. Catch it and return nothing to avoid an annoying (but harmless?) routing error.
    post ":user_name/upload" => :create, :as => :handle_upload
    delete ":user_name/postings/upload_destroy/:id" => :destroy, :as => :upload_destroy
  end


  scope ":user_name", :as => "user" do
    match "postings/:id/conversations" => redirect("/conversations/postings/%{id}")
    post "postings/new" => "postings#create"
    get "postings" => redirect("/%{user_name}/")
    resources :postings
  end

  controller :postings do
    match ":user_name/postings/:id/delist_posting_modal" => :load_delist_modal, :as => :load_delist_modal
    match ":user_name/postings/:id/promote_posting_modal" => :load_promote_modal, :as => :load_promote_modal
    match ":user_name/postings/:id/load_email_share_modal" => :load_email_share_modal, :as => :load_email_share_modal
    match ":user_name/postings/:id/delist_posting" => :delist_posting, :as => :delist_posting
    match ":user_name/postings/:id/relist_posting" => :relistPosting, :as => :relist_posting
    match ":user_name/postings/:id/relist_posting_copy" => :relistPostingCopy, :as => :relist_posting_copy
    match ":user_name/postings/:id/postToCraigslist" => :postToCraigslist, :as => :post_to_craigslist
    match ":user_name/postings/:id/posting_to_craigslist" => :craigslist_loading, :as => :craigslist_loading
    post ":user_name/postings/:id/craigslist_ajax" => :craigslist_ajax, :as => :craigslist_ajax
    post ":user_name/postings/:id/promote_posting_by_email" => :promote_posting_by_email, :as => :promote_posting_by_email
    match "postings/:id/remove_completed_posting" => :remove_completed_posting, :as => :remove_completed_posting
    match "get_custom_fields" => :get_custom_fields
    post 'categorize_posting' => :categorize_posting
    post 'new_posting_form_for_category' => :new_posting_form_for_category
    match 'form_data_for_bookmark' => :form_data_for_bookmark, :as => :form_data_for_bookmark
    get "all" => :all_postings
    match "post_from_bookmark" => :post_from_bookmark, :as => :post_from_bookmark
    match "promote_to_facebook_from_modal" => :promote_to_facebook_from_modal, :as => :promote_to_facebook_from_modal
    get "reppio_picks" => :reppio_picks_index
    match "toggle_reppio_pick" => :toggle_reppio_pick, :as => :toggle_reppio_pick
    get "remove_listings" => :remove_listings
    match "remove_listing" => :remove_listing, :as => :remove_listing
    match 'data_feed.:format' => :google_feed
  end

  resources :conversations, :only => [:create, :update]
  controller :conversations do
    match "conversations/:id/remove" => :remove_conversation, :as => :remove_conversation
    match "message_from_new_user" => :message_from_new_user, :as => :message_from_new_user
    match "create_conversation_with_offer" => :create_with_offer, :as => :create_conversation_with_offer
    match "load_message_modal/:id" => :load_message_modal, :as => :load_message_modal
  end

  controller :users do
    put "add_autogroup_email" => :add_autogroup_email, :as => :add_autogroup_email
    get "vendors" => :rep_it, :as => :rep_it
    get "repit" => :rep_it, :as => :rep_it
    get "rep-it" => :rep_it, :as => :rep_it
    get "rep_it" => :rep_it, :as => :rep_it
    get "rep_it_bookmark" => :rep_it_bookmark, :as => :rep_it_bookmark
    get "settings" => :settings, :as => :settings
    put "settings" => :update
    get "signup" => :new
    get "email_sign_up" => :email_sign_up
    post "email_sign_up" => :create
    get "create_user_name" => :create_user_name, :as => :create_user_name
    post "verify_phone_text" => :send_cell_phone_verification_text
    post "verify_phone" => :verify_cell_phone_number
    put ":user_name" => :update
    post "deactivate" => :deactivate
    match 'confirm_secondary_email' => :confirm_secondary_email, :as => :confirm_secondary_email
    match 'send_confirmation_secondary_email' => :send_confirmation_secondary_email, :as => :send_confirmation_secondary_email
    match 'cancel_secondary_email_confirmation' => :cancel_secondary_email_confirmation, :as => :cancel_secondary_email_confirmation
    post 'reset_password' => :reset_password, :as => :reset_password
    match 'send_confirmation_email' => :send_confirmation_email, :as => :send_confirmation_email
    match 'confirm' => :confirm, :as => :confirm
    match ":user_name/edit" => :edit, :as => :edit_user
    match ":user_name/reviews" => :user_reviews, :as => :user_reviews
    get ":user_name" => :show, :as => :user
  end

app/views/users/_feedback.html.erb
<% content_for :feedback_active, "true" %>

<div class="row-fluid row-fluid-style">
  <div class="span12">
    <div class="rep_container" style="padding:20px; -webkit-box-shadow:none; -moz-box-shadow:none; box-shadow: none;">
      <h2>Please provide any feedback below.</h2>
      <hr style="border-bottom:0px;">

      <%= form_for current_user do |f| %>
          <div class="row-fluid">
            <div class="span12">
              <b>What browser are you using?</b>
              <br>
              <%= f.text_area :feedback_manage, :rows=>1, :style=>"width:300px", :placeholder=>"e.g. Firefox, Internet Explorer 7, Chrome" %>
              <br>

              <b>What page(s) are you commenting on?</b><br>
              <%= f.text_area :feedback_create, :rows=>1, :style=>"width:300px", :placeholder=>"e.g. Search and manage page" %>
              <br>

              <b>General feedback</b>
              <br>
              <%= f.text_area :feedback_search, :rows=>10, :style=>"width:500px", :placeholder=>"Reppio is awesome, but (1) blah blah blah, and (2) yadda yadda yadda, would make it even better!" %>

              <br>
            </div>
          </div>
          <%= submit_tag "Save and submit feedback", :class=>"btn btn-success btn-large" %>
          <br><br>
          Thanks again! You can always come back and add to or change this form.
      <% end %>
    </div>
  </div>
</div>

app/views/users/_signUpForm.html.erb
<div style="font-size:1.4em; font-weight:400;">Buy and sell with reputable people.</div>
  <div style="color:#000;margin-top:20px; margin-bottom: 10px;">
    <%= image_tag 'modal/meg-bubble.png', :class=>"meg-bubble" %><%= rep_meter_large(98, "rep-score-inline") %>
  </div>

  <div id="fbSignup" style="font-size:1.1em; line-height:1.3em; text-align:center;">
    <div style="margin-bottom:10px;">
      <br>
      <a class="fb-auth btn-facebook" style="color:white;" href="/auth/facebook?origin=<%= "http://#{request.host}#{request.fullpath}" %>" target = '_blank'>Sign up with Facebook</a>
      <br><br>
      <span style="color:#777777; font-size:0.9em;"><i class="icon-lock" style="font-size:1.3em;"></i> We'll never post without your permission.</span>
    </div>
    <hr style="border-bottom:0px;">
    <a id="emailSignupLink"><i class="icon-envelope"></i>&nbsp;&nbsp;Sign up without Facebook</a>
  </div>

  <div id="emailSignup" style="display:none; text-align:center;margin-top:20px;">

    <%= form_for new_user_from_modal=User.new, :url => email_sign_up_path, :validate => true do |f| %>
            <% new_user_from_modal.email_addresses.build%>
            <%= f.fields_for :email_addresses do |ef| %>
                <span class="controls">
                  <%= ef.text_field :email, :placeholder=>"email", :id=>"email" %>
                  <%= ef.hidden_field :is_primary, :value => true %>
                </span>
            <% end %>
              <%= f.text_field :first_name, :placeholder=>"first name"  %>
              <%= f.text_field :last_name, :placeholder=>"last name" %>

              <%= f.password_field :password, :placeholder=>"password", :id=>"password" %>

          <%= f.hidden_field :origin_if_facebook_sign_up, :value => request.referer %>

          <br>
          <%= f.submit "Sign Up", :class => "rep-btn rep-btn-orange" %>
          <br><br>

          <a class="fb-auth blue-link" href="/auth/facebook?origin=<%= "http://#{request.host}#{request.fullpath}" %>" data-width="420" data-height="440">Sign
            up with Facebook instead.</a>
    <% end %>
  </div>


<script type="text/javascript">
        function popupCenter(url, width, height, name) {
            var left = (screen.width / 2) - (width / 2);
            var top = (screen.height / 2) - (height / 2);
            return window.open(url, name, "menubar=no,toolbar=no,status=no,width=" + width + ",height=" + height + ",toolbar=no,left=" + left + ",top=" + top);
        }

        $("a.fb-auth").click(function (e) {
            popupCenter($(this).attr("href"), 420, 440, "authPopup");
            e.stopPropagation();
            return false;
        });
        $('#emailSignupLink').click(function() {
            $('#fbSignup').hide();
            $('#emailSignup').fadeIn();
        });
</script>

app/views/users/add_autogroup_email.js.erb
$('#joinGroupModal .modal-body').html('Please check your inbox to verify that you own the email address.');
setTimeout(function(){ $('#joinGroupModal').modal('hide');}, 3000);

app/views/users/confirm.html.erb
<div class="row-fluid row-fluid-style">
<div class="rep_container" style="padding:20px;">
  <h4>
<% if @confirmation_success %>

      Hi <%= @user.first_name %>! You have successfully verified your email address. Log in from the top menu to get started.

  <% else %>

      Hi
      <% if !current_user.nil? %> <%= current_user.first_name %>
      <% end %>! Unfortunately, there was an error in the email confirmation code and
      your email address could not be verified. After logging in from the top menu, click "Send Email to Confirm Email Address" (accessible from the dropdown on the top menu) to try again.

  <% end %>
</h4>
</div>
    </div>

app/views/users/edit.html.erb
<% content_for :headContent do -%>
    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css" %>
<% end %>


<% title "Reppio: Edit Profile" %>
<% content_for :center_content do %>

    <h3>
      Edit Your Profile
    </h3>

          <div class="row">
              <div class="span4">
                <div class="well">
                  <h4>Drag and drop images below</h4>
                  <%= render :partial => "fileupload/main", :locals => {:upload => @upload} %>
                </div>
              </div>

              <div class="span5">
                <%= form_for @user, :html => {:multipart => true, :class => "form-horizontal primaryForm edit-user-form"}, :validate => true do |f| %>

                    <% if current_user.errors.any? %>
                        <div id="error_explanation">
                          <h2 class="alert alert-error"><%= pluralize(current_user.errors.count, "error") %> prevented this user from
                            being saved:</h2>

                          <% current_user.errors.full_messages.each do |msg| %>
                              <p><span class="label label-primary">Error:</span> <%= msg %> </p>
                          <% end %>
                        </div>
                    <% end %>
                    <div class="control-group">
                      <%= f.label :first_name, :class => "control-label" %>
                      <div class="controls">
                        <%= f.text_field :first_name, :style => "width:100%" %>
                      </div>
                    </div>


                    <div class="control-group">
                      <%= f.label :last_name, :class => "control-label" %>
                      <div class="controls">
                        <%= f.text_field :last_name, :style => "width:100%" %>
                      </div>
                    </div>


                    <div class="<%= params[:highlight] ? "paypal-highlight" : "" %>">
                    <div class="control-group">
                      <%= f.label :email, :class => "control-label" %>
                      <div class="controls">
                        <input id="disabledInput" class="input-large disabled" type="text" disabled="" placeholder="<%= current_user.email %>" style="width:100%">
                        <% @non_primary_validated_emails.each do |email| %>
                            <input id="disabledInput" class="input-large disabled" type="text" disabled="" placeholder="<%= email.email %>" style="width:100%">
                            <br>
                        <% end %>
                        <% if @pending_email.blank? %>
                            <div>
                              <a id="add-email-link" class="blue-link" style="cursor:pointer;">add another email address</a>
                            </div>

                        <% else %>
                            <div style=" border-style:solid; padding: 20px;margin-top: 20px;width:80%; background-color: #FFE2E2;">
                              Please check your email at <%= @pending_email[0].email %> to verify the address.<br><br>
                              <%= link_to "Resend confirmation email", send_confirmation_secondary_email_url, :class => "blue-link" %>
                              · <%= link_to "Cancel", cancel_secondary_email_confirmation_url, :class => "blue-link" %>
                            </div>
                        <% end %>
                        <label class="checkbox inline small-text" for="user_email_private">
                          <%= f.check_box :email_private, {:checked => current_user.email_private?} %>
                          Private
                        </label>
                      </div>
                    </div>

                    <div class="control-group">
                      <%= f.label :paypal_email, :class => "control-label" %>
                      <div class="controls">
                        <% if current_user.paypal_email.blank?
                           potential_emails = @non_primary_validated_emails.collect(&:email)<<current_user.email<< ''
                        else
                          potential_emails = @non_primary_validated_emails.collect(&:email)<<current_user.email
                        end%>
                        <%= f.select :paypal_email, potential_emails.reverse, {:default => current_user.paypal_email}, :style => "width:100%" %>
                      </div>
                    </div>
                    </div>

                    <div class="control-group">

                      <%= f.label :phone, :class => "control-label" %>

                      <div class="controls">
          <span class="hasTooltip" title="If you change your cellphone number, you need to reverify it.">
            <%= f.text_field :phone_number, :class => "phone-number", :style => "width:100%" %>
          </span>
                        <label class="checkbox inline small-text" for="user_phone_number_private">
                          <%= f.check_box :phone_number_private, {:checked => current_user.phone_number_private?} %>
                          Private
                        </label>
                        <% if current_user.cell_phone_verified %>
                            <h6>VERIFIED</h6>
                        <% end %>
                      </div>
                    </div>

                    <div class="control-group">
                      <%= f.label(:about_me, :class => "control-label") %>
                      <div class="controls">
                        <%= f.text_area :about_me, :class => "input-large", :rows => 3, :style => "width:100%" %>
                      </div>
                    </div>


                    <div class="control-group">
                      <%= f.label :education, :class => "control-label" %>
                      <div class="controls">
                        <%= f.text_field :education, :style => "width:100%" %>
                        <label class="checkbox inline small-text" for="user_education_private">
                          <%= f.check_box :education_private, {:checked => current_user.education_private?} %>
                          Private
                        </label>
                      </div>
                    </div>

                    <div class="control-group">
                      <%= f.label :employer, :class => "control-label" %>
                      <div class="controls">
                        <%= f.text_field :employer, :style => "width:100%" %>
                        <label class="checkbox inline small-text" for="user_email_private">
                          <%= f.check_box :employer_private, {:checked => current_user.employer_private?} %>
                          Private
                        </label>
                      </div>
                    </div>


                    <div class="control-group">
                      <%= f.label(:zip_code, :class => "control-label") %>
                      <div class="controls">
          <span class="hasTooltip" title="Only the city and state will be made public.">
            <%= f.hidden_field :street_address, :class => "street-address" %>
            <%= f.hidden_field :city, :class => "city" %>
            <%= f.hidden_field :state, :class => "state" %>
            <%= f.text_field :zip_code, :class => "zip-code", :id => 'searchTextField', :style => "width:100%" %>
          </span>
                      </div>
                    </div>
                    <% if !@sortedPictures.empty? %>
                        <div class="control-group">
                          <%= f.label :pictures, :class => "control-label" %>
                          <div class="controls">


                            <ul id="pictures">
                              <% @sortedPictures.each do |pictureObj| %>
                                  <li id="p<%= pictureObj[1] %>" class="ui-state-default">
                                    <div class="closeButton" title="Close"></div>
                                    <%= image_tag pictureObj[0].photo.url(:thumb) %>
                                  </li>
                              <% end %>
                            </ul>

                          </div>
                        </div>
                    <% end %>
                    <%= f.hidden_field :uploaded_pictures, :id => "uploaded_pictures", :value => "" %>
                    <%= f.hidden_field :picture_display_order, :class => "picture_display_order" %>

                    <%= submit_tag "Update your profile", :class => "rep-btn rep-btn-orange" %>
                    <br><br>
                <% end %>
              </div>
            </div>

<% end %>

<%= render :template => "manage/manage" %>




<%= google_maps_script %>


<script type="text/javascript">
    $(".hasTooltip").tooltip();

    $('#add-email-link').click(function () {
        $(this).replaceWith('<input data-validate="true" id="user_email_addresses_attributes_<%= current_user.email_addresses.length-1 %>_email" name="user[email_addresses_attributes][<%= current_user.email_addresses.length-1 %>][email]" size="30" style="width:100%" type="text">');
        window['edit_user_<%= current_user.id%>']["validators"]["user[email_addresses_attributes][<%= current_user.email_addresses.length-1 %>][email]"] = {"format":{"message":"not a valid email", "with":/^[\w+\-.]+@[a-z\d\-.]+\.[a-z]+$/i}, "uniqueness":{"message":"has already been taken", "case_sensitive":false}};
    });
</script>

<%= javascript_include_tag 'zipCodeMinimum' %>

app/views/users/email_has_been_sent.html.erb
<div class="body-wrapper">

  Hi <%= @user.first_name %>! An email has been sent to <%= @user.email %>. Click the link in the email
  to finish the sign-up process.

</div>

app/views/users/new.html.erb
<% title "Sign Up for Reppio" %>
<div class="rep-container" style="margin:0 auto; text-align:center; width:400px; padding-bottom:30px;">
  <br>
  <%= render(:partial => "signUpForm") %>
</div>

app/views/users/omniauth_failure.html.erb
<script type="text/javascript">
    $(document).ready(function () {
        window.close();
    });
</script>

<div class="body-wrapper">
  You cancelled connecting with Facebook.
</div>

app/views/users/rep_it.html.erb
<div class="row">
  <div class="span2 offset"></div>
  <div class="span8">
    <div class="rep-container container" style="padding:20px;">
      <h1>WOW! Publish posts from Etsy, eBay, and Craigslist instantly! </h1>

      <p>Introducing the ‘Rep it’ button. Once installed (within seconds), this magical button allows you to instantly publish your posts from other websites to Reppio with one simple click. Seriously, give it a try, you'll freak at how cool it is.
        </p>
      <h2>It's free. It's easy. Why not?  </h2>
      <% if current_user %>

            <a title="Rep it!" class="rep-it-button" onclick="window.alert('To install the \'Rep it\' button, drag it to your bookmark bar. Or right-click and choose \'Add to Favorites.\'');return false;" href="javascript:void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src', '<%= rep_it_bookmark_url(:u => current_user.rep_it_token) %>');document.body.appendChild(e)})());">Rep
              it</a>   Drag me into your bookmark toolbar.
      <% else %>
          You must be logged in to use the Rep it! button.
      <% end %>

      <hr>
     <h3> Get started</h3>
      <p>
      You must sign in to activate your personalized button. If you're not already a member, join for free. It's easy and only takes a few seconds. You can even join with Facebook.
      </p>
      <h3> Grab it </h3>

      Drag the "Rep it" button to your browser bookmark bar. On some browsers, you may need to right-click and choose "Add to Favorites." Remember, if you're not signed in, it won't work!
      <h3>  Rep it </h3>

      Navigate to your item on Etsy, Craigslist, or eBay and click the 'Rep it' button. Magically, all your info — title, description, price, location, photos — will be copied. Click "Publish" (or "save as draft") and you're done!
      <h3>Repeat it </h3>

      Do it again and again for all your other items. It's so quick and easy. Just don't get carried away and start listing other peoples' stuff!
       <hr>
      <h2>FAQ</h2>

      <h3>Where does it work?</h3>

      The button was designed to work on Etsy, Craigslist, and eBay. If you have a suggestion for another website it should support, let us know at team@reppio.com.
      <h3>Am I breaking the 'Terms of Use' of the other website?</h3>

      Nope. As long as the text and photos are yours, everything is kosher.

      <h3>Do I have to be signed into Reppio to use the button? </h3>

      No. We only need you to be signed in when you install the button. Once it is installed, it carries an account access token that is unique to you.
      <h3>Is it secure?</h3>

      Yes. We take security seriously at Reppio. Just remember, if you install it on a computer that is not yours (Internet cafe or friend's computer), you'll want to uninstall it when you're done. You can do this by dragging it off the Bookmark Bar.
      <h3>It's not working!</h3>

      Let us know at team@reppio.com. Please include the URL of the post you are trying to list and what browser/operating system you are using.

    </div>
  </div>

</div>

app/views/users/send_cell_phone_verification_text.js.erb
$('#text-sent').html("<div class='alert-info'>Text sent! When you receive the confirmation code, enter it below.</div>");
$('.phone-confirmation-form').slideDown();

app/views/users/verify_cell_phone_number.js.erb
$('#verify-phone-section').html('<%= image_tag("verification_icons/check.jpg", :size => "20x20") %><b>&nbsp;&nbsp;Phone Verified</b>');