config/routes.rb
    get "handle_request" => :handle_request_join_group, :as => :handle_request
    get "/groups/:id/invite_to_group" => :invite_to_group, :as => :invite_to_group
    post "/groups/send_email_to_invite_to_group" => :send_email_to_invite_to_group
    post "invite_facebook_connections_to_group" => :invite_facebook_connections_to_group
    get "notifications" => :notifications, :as => :groups_notifications
    get "join_autogroup_modal" => :join_autogroup_modal, :as => :join_autogroup_modal
  end

  controller :payments do
    match "submit_deposit" => :submit_deposit, :as => :submit_deposit
    match "buy" => :buy, :as => :buy
    match "do_deposit" => :do_express_checkout_payment_for_deposit, :as => :do_express_checkout_payment_for_deposit
    match "payments/ipn_notification/:id/" => :ipn_notification, :as => :ipn_notification
    get "payments/canceled_payment_request" => :canceled_payment_request, :as => :canceled_payment
    get "payments/completed_payment_request/:id/" => :completed_payment_request, :as => :completed_payment
    get "payments/failed_payment" => :failed_payment, :as => :failed_payment
    post "request_payment" => :request_payment, :as => :request_payment
    match "cancel_request_payment" => :cancel_request_payment, :as => :cancel_request_payment
  end

  controller :manage do
    get "manage/selling" => :selling, :as => :manage_selling
    get "manage/buying" => :buying, :as => :manage_buying
    get "manage/completed_buying" => :completed_buying, :as => :manage_completed_buying
    get "manage/completed_selling" => :completed_selling, :as => :manage_completed_selling
    get "manage/drafts_selling" => :drafts_selling, :as => :manage_drafts_selling

    get "manage/selling/:id" => :selling_posting_conversations, :as => :selling_posting_conversations
    get "manage/buying/:id" => :buying_posting_conversation, :as => :buying_posting_conversation
    get "manage/completed_selling/:id" => :completed_selling_posting_conversations, :as => :completed_selling_posting_conversations
    get "manage/completed_buying/:id" => :completed_buying_posting_conversation, :as => :completed_buying_posting_conversation
    get "manage/drafts_selling/:id" => :drafts_selling_redirect

    get "manage/selling/:id/:buyer_id" => :selling_posting_conversation, :as => :selling_posting_conversation
    get "manage/completed_selling/:id/:buyer_id" => :completed_selling_posting_conversation, :as => :completed_selling_posting_conversation

    match "manage" => redirect("/manage/selling"), :as => :manage

    get "repscore" => :repscore, :as => :repscore

    get "manage/reviews" => :reviews

    match "manage/add_student_email" => :add_student_email
    match "manage/rep_center_references" => :rep_center_references, :as => :rep_center_references
    match "manage/rep_center_referrals" => :rep_center_referrals, :as => :rep_center_referrals
    match "rep_center" => redirect("/manage/reviews"), :as => :rep_center
    match "verifications" => :verifications, :as => :verifications
    match "reputation_explained" => :reputation_explained, :as => :reputation_explained

    get "manage/interests" => :interests, :as => :interests
    match "toggle_interest" => :toggle_interest, :as => :toggle_interest

    get "conversations" => :redirect_to_conversation
    get "conversations/:id" => :redirect_to_conversation

  end

  controller :watchlist do
    match "watchlist/bookmarks" => :bookmarks
    match "watchlist/alert" => :alert, :as => :search_alert
    match "watchlist" => redirect("/watchlist/bookmarks"), :as => :watchlist
  end

  controller :bookmarks do
    post "bookmarks" => :toggle
    match "bookmarks/:posting_id" => :toggle
  end


  resources :alerts, :only => [:create, :edit, :destroy, :update]

  controller :static do
    match "about" => :about
    match "jobs" => :jobs
    match "faq" => :faq
    match "terms" => :terms
    match "privacy" => :privacy
    match "team" => :team
    match "press" => :press
    match "app" => :app
    get "contact" => :contact
    post "contact" => :contactSend
  end


  resources :references
  controller :references do
    match "contacts/:importer/callback" => :invite
    match "contacts/failure" => :failure
    post "references/send_invites_list" => :send_invites_list
    post "references/send_references_given_email_list" => :send_references_given_email_list
    post "accept_or_reject_references" => :accept_or_reject_references, :as => :accept_or_reject_references

  end

  post 'flag', :to => 'flags#create', :as => :flag

  controller :reviews do
    get "reviews" => :index, :as => :my_reviews
    post "reviews/vote" => :vote, :as => :review_vote
    post "reviews" => :create
    match "reviews/:id" => :respond, :as => :respond_to_review
  end

  controller :browse do
    match "search" => :show, :as => :search
    match "search_json" => :autocomplete
    match "load_mini_map", :load_mini_map, :as => :load_mini_map
  end

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "login" => :destroy
    get "jackterminal" => :jack_signin
    post "jackterminal" => :jack_create
    get "interstitial" => :interstitial, :as => :interstitial
    match "interstitial/*redirect" => :interstitial, :as => :interstitial
    match "logout" => :destroy, :as => :logout
    match 'auth/facebook/callback' => :create_auth
    match 'auth/twitter/callback' => :twitter
    match 'auth/linkedin/callback' => :linkedin
    match 'auth/failure' => :failure
  end

  controller :mobile do
    match "mobile/posting/categorize2" => :mobile_posting_categorize2
    match "mobile/posting/create2" => :mobile_posting_create2
    match "mobile/toggle/push" => :mobile_toggle_push
    match "mobile/group/info" => :group_info

    get "mobile/app/version" => :mobile_app_version
    match "mobile/auth/:provider/callback" => :mobile_create_auth
    match "mobile/login" => :mobile_create
    match "mobile/profile/update" => :mobile_profile_update
    match "mobile/profile/get" => :mobile_profile_get
    match "mobile/posting/categorize" => :mobile_posting_categorize
    match "mobile/posting/create" => :mobile_posting_create
    match "mobile/posting/get" => :mobile_posting_get
    match "mobile/posting/update" => :mobile_posting_update
    match "mobile/fields/get" => :mobile_fields_get
    match "mobile/fields/get2" => :mobile_fields_get2
    match "mobile/manager/get" => :mobile_manager_get
    match "mobile/messages/get" => :mobile_messages_get
    match "mobile/conversation/create" => :mobile_conversation_create
    match "mobile/conversations/get" => :mobile_conversations_get
    #match "mobile/manager/buying"=>:mobile_manager_buying
    #match "mobile/manager/selling"=>:mobile_manager_selling
    match "mobile/conversation/update" => :mobile_conversation_update
    match "mobile/email/signup" => :mobile_email_signup
    match "mobile/categories/all" => :mobile_categories_all
    match "mobile/alert/create" => :mobile_alert_create
    match "mobile/alert/remove" => :mobile_alert_remove
	match "mobile/alert/edit" => :mobile_alert_edit
	
    match "mobile/transaction/complete" => :mobile_transaction_complete
    match "mobile/transaction/cc" => :mobile_transaction_cc

    match "mobile/push/setup" => :mobile_push_setup
    match "mobile/push/setup/android" => :mobile_push_setup_android
    #TODO remove after testing
    match "mobile/push/send/android" => :mobile_push_send_android
    match "mobile/push/conversation/get" => :mobile_push_conversation_get

    match "mobile/posting/agree/sell" => :mobile_posting_agree_sell
    match "mobile/posting/cancel/sell" => :mobile_posting_cancel_sell

    match "mobile/payments/transact/cc" => :mobile_payments_transact_cc
    match "mobile/payments/set/seller" => :mobile_payments_set_seller
    match "mobile/payments/set/buyer" => :mobile_payments_set_buyer
    match "mobile/payments/get/cards" => :mobile_payments_get_cards
    match "mobile/payments/get/card" => :mobile_payments_get_card
    match "mobile/payments/update/card" => :mobile_payments_update_card
    match "mobile/payments/invalidate/card" => :mobile_payments_invalidate_card

    match "mobile/payments/get/bankAccounts" => :mobile_payments_get_bankAccounts
    match "mobile/payments/get/bankAccount" => :mobile_payments_get_bankAccount
    match "mobile/payments/delete/bankAccount" => :mobile_payments_delete_bankAccount

    match "mobile/browse" => :browse
    match "mobile/search" => :search
    match "mobile/listing_details_view" => :listing_details_view

    match "mobile/return_groups" => :return_groups

    match "mobile/toggle_bookmark" => :toggle_bookmark
    match "mobile/return_bookmarks" => :return_bookmarks


    match "mobile/join_group" => :join_group
    match "mobile/leave_group" => :leave_group

    match "mobile/onboarding_add_interests" => :onboarding_add_interests
    match "mobile/onboarding_add_school_email" => :onboarding_add_school_email


    match "mobile/reset_password" => :reset_password
	
	match "mobile/get_alerts"=>:get_alert_labels
	match "mobile/get_alert_postings"=>:get_alert_postings
	
	match "mobile/queue_cg"=>:queue_craigslist_post
  end


  controller :upload do
    get ":user_name/upload" => :catchGet #Not sure why; simply setting a form :url => handle_upload_url (as in fileupload/_main) will cause a get call to said URL. Catch it and return nothing to avoid an annoying (but harmless?) routing error.
    post ":user_name/upload" => :create, :as => :handle_upload
    delete ":user_name/postings/upload_destroy/:id" => :destroy, :as => :upload_destroy
  end


  scope ":user_name", :as => "user" do
    match "postings/:id/conversations" => redirect("/conversations/postings/%{id}")
    post "postings/new" => "postings#create"
    get "postings" => redirect("/%{user_name}/")
    resources :postings
  end

  controller :postings do
    match ":user_name/postings/:id/delist_posting_modal" => :load_delist_modal, :as => :load_delist_modal

app/controllers/watchlist_controller.rb
class WatchlistController < ApplicationController
  def show
  end

  def alert
    @alert = Alert.find(params[:alert_id])
    if @alert.num_new_listings > 0
      current_user.update_attribute(:alerts_badge_count, current_user.alerts_badge_count - @alert.num_new_listings)
      @alert.update_attribute(:num_new_listings, 0)
    end
    @alertedPostings = @alert.postings

  end

  def bookmarks
    bookmarks = Bookmark.find_all_by_user_id(current_user.id)
    @bookmarkedPostings = bookmarks.collect { |b| Posting.find(b.posting_id) }.reverse
  end
end

app/views/watchlist/_watchlist_menu.html.erb
<div id="manage-menu-left">
  <div id="watchlist-bookmarks" class="manage-menu">
    <div class="manage-menu-header" <%= content_for(:activeManageMenu) == "bookmarks" ? "style=font-weight:bold;" : "" %>>
      <%= link_to watchlist_url do %>
          <span style="color:#333;">Bookmarks</span>
      <% end %>
    </div>
  </div>
  <div id="watchlist-alerts" class="manage-menu">
    <div class="manage-menu-header<%= !alertKeywords.empty? ? " manage-menu-header-active" : '' %>" id="manage-sell-link">
      Alerts
    </div>

    <% if alertKeywords.blank? %>
        <div class="manage-menu-subitem" href="#createAlertModal" role="button" data-toggle="modal">
          &nbsp;&nbsp;<i class="icon-plus"></i> Create Alert
        </div>
        <%= render(:partial => "alerts/create_alert_modal", :locals => {:is_new => "true"}) %>
    <% else %>
        <% alertKeywords.each do |alert| %>
            <%= link_to search_alert_url(:alert_id => alert.id) do %>
                <div class="manage-menu-subitem <%= content_for(:activeManageMenu) == alert.search ? "manage-menu-subitem-active" : "" %>">
                  &nbsp;&nbsp;"<%= alert.search %>"
                  <%= badge(alert.num_new_listings) %>
                </div>
            <% end %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/watchlist/alert.html.erb
<% title "Reppio Watchlist: Alerts" %>
<% content_for :activeManageMenu, @alert.search %>

<% content_for :center_content do %>

    <div style="padding-right:45px;">

      <h3 style="margin-top:0px;">Your Alert</h3>


      Listings with <b>"<%= @alert.search %>"</b> within <b><%= @alert.radius %> miles</b> of <b><%= @alert.address %></b> less than <b><%= number_to_currency(@alert.max_price) %></b>
      &nbsp;&nbsp;&nbsp;
      <%= link_to 'Edit', edit_alert_url(:id => @alert.id), :remote=>true %>  &nbsp;&nbsp;&nbsp;
      <%= link_to 'Remove', alert_path(:id => @alert.id), :method => :delete, :remote=>true %>

      <hr>
    </div>

    <%= render(:partial => "manage/postings_list",
               :locals => {:postings => @alertedPostings, :type=>"alerts"}) %>
<% end %>

<%= render :template => "watchlist/show" %>

app/views/watchlist/bookmarks.html.erb
<% title "Reppio Watchlist: Bookmarks" %>
<% content_for :activeManageMenu, "bookmarks" %>

<% content_for :center_content do %>

    <div style="padding-right:45px;">
    <h4>Bookmarked Listings</h4>

    Bookmarks are an easy way to remember items you are interested in. You can bookmark items from the Browse section, or from each listing's detail page.

    <hr>
    </div>

    <%= render(:partial => "manage/postings_list",
               :locals => {:postings => @bookmarkedPostings, :type=>"bookmark"}) %>
<% end %>

<%= render :template => "watchlist/show" %>

app/views/watchlist/show.html.erb
<% content_for :watchlist_active, "true" %>
<% content_for :blue_header_image_height, "400" %>

<div id='listings-loader'>
  <%= image_tag 'squares-circle-loader.gif' %>
</div>

<div class="posting-title">Your Watchlist</div>

<div class="rep-container">
  <div class="row">
    <div class="span12 rep-container" id="manage-menu-and-content" style="margin-top:-7px; overflow:hidden;">
      <div class="span2 equal-height-column dark-grain-background">
        <%= render(:partial => "watchlist_menu", :locals => {:alertKeywords => current_user_alerts}) %>
      </div>
      <div class="span10">
        <div class="rep-container equal-height-column" id="manage-content" style="padding:20px 20px 9999px 20px;">
          <%= yield :center_content %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

    function scripts_on_new_manage_page() {
        $('#manage-menu-left a').click(function () {
            $.pjax({
                container:'#manage-menu-and-content',
                fragment:'#manage-menu-and-content',
                url:$(this).attr('href'),
                timeout:5000
            });
            return false;
        });
    }

    scripts_on_new_manage_page();

    $.pjax.defaults.scrollTo = false;
    $(document).on('pjax:beforeSend',function () {
        $('#listings-loader').show();
    }).on('pjax:success', function () {
                $('#listings-loader').hide();
                scripts_on_new_manage_page();
            });

</script>