config/routes.rb
    get "manage/completed_buying" => :completed_buying, :as => :manage_completed_buying
    get "manage/completed_selling" => :completed_selling, :as => :manage_completed_selling
    get "manage/drafts_selling" => :drafts_selling, :as => :manage_drafts_selling

    get "manage/selling/:id" => :selling_posting_conversations, :as => :selling_posting_conversations
    get "manage/buying/:id" => :buying_posting_conversation, :as => :buying_posting_conversation
    get "manage/completed_selling/:id" => :completed_selling_posting_conversations, :as => :completed_selling_posting_conversations
    get "manage/completed_buying/:id" => :completed_buying_posting_conversation, :as => :completed_buying_posting_conversation
    get "manage/drafts_selling/:id" => :drafts_selling_redirect

    get "manage/selling/:id/:buyer_id" => :selling_posting_conversation, :as => :selling_posting_conversation
    get "manage/completed_selling/:id/:buyer_id" => :completed_selling_posting_conversation, :as => :completed_selling_posting_conversation

    match "manage" => redirect("/manage/selling"), :as => :manage

    get "repscore" => :repscore, :as => :repscore

    get "manage/reviews" => :reviews

    match "manage/add_student_email" => :add_student_email
    match "manage/rep_center_references" => :rep_center_references, :as => :rep_center_references
    match "manage/rep_center_referrals" => :rep_center_referrals, :as => :rep_center_referrals
    match "rep_center" => redirect("/manage/reviews"), :as => :rep_center
    match "verifications" => :verifications, :as => :verifications
    match "reputation_explained" => :reputation_explained, :as => :reputation_explained

    get "manage/interests" => :interests, :as => :interests
    match "toggle_interest" => :toggle_interest, :as => :toggle_interest

    get "conversations" => :redirect_to_conversation
    get "conversations/:id" => :redirect_to_conversation

  end

  controller :watchlist do
    match "watchlist/bookmarks" => :bookmarks
    match "watchlist/alert" => :alert, :as => :search_alert
    match "watchlist" => redirect("/watchlist/bookmarks"), :as => :watchlist
  end

  controller :bookmarks do
    post "bookmarks" => :toggle
    match "bookmarks/:posting_id" => :toggle
  end


  resources :alerts, :only => [:create, :edit, :destroy, :update]

  controller :static do
    match "about" => :about
    match "jobs" => :jobs
    match "faq" => :faq
    match "terms" => :terms
    match "privacy" => :privacy
    match "team" => :team
    match "press" => :press
    match "app" => :app
    get "contact" => :contact
    post "contact" => :contactSend
  end


  resources :references
  controller :references do
    match "contacts/:importer/callback" => :invite
    match "contacts/failure" => :failure
    post "references/send_invites_list" => :send_invites_list
    post "references/send_references_given_email_list" => :send_references_given_email_list
    post "accept_or_reject_references" => :accept_or_reject_references, :as => :accept_or_reject_references

  end

  post 'flag', :to => 'flags#create', :as => :flag

  controller :reviews do
    get "reviews" => :index, :as => :my_reviews
    post "reviews/vote" => :vote, :as => :review_vote
    post "reviews" => :create
    match "reviews/:id" => :respond, :as => :respond_to_review
  end

  controller :browse do
    match "search" => :show, :as => :search
    match "search_json" => :autocomplete
    match "load_mini_map", :load_mini_map, :as => :load_mini_map
  end

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "login" => :destroy
    get "jackterminal" => :jack_signin
    post "jackterminal" => :jack_create
    get "interstitial" => :interstitial, :as => :interstitial
    match "interstitial/*redirect" => :interstitial, :as => :interstitial
    match "logout" => :destroy, :as => :logout
    match 'auth/facebook/callback' => :create_auth
    match 'auth/twitter/callback' => :twitter
    match 'auth/linkedin/callback' => :linkedin
    match 'auth/failure' => :failure
  end

  controller :mobile do
    match "mobile/posting/categorize2" => :mobile_posting_categorize2
    match "mobile/posting/create2" => :mobile_posting_create2
    match "mobile/toggle/push" => :mobile_toggle_push
    match "mobile/group/info" => :group_info

    get "mobile/app/version" => :mobile_app_version
    match "mobile/auth/:provider/callback" => :mobile_create_auth
    match "mobile/login" => :mobile_create
    match "mobile/profile/update" => :mobile_profile_update
    match "mobile/profile/get" => :mobile_profile_get
    match "mobile/posting/categorize" => :mobile_posting_categorize
    match "mobile/posting/create" => :mobile_posting_create
    match "mobile/posting/get" => :mobile_posting_get
    match "mobile/posting/update" => :mobile_posting_update
    match "mobile/fields/get" => :mobile_fields_get
    match "mobile/fields/get2" => :mobile_fields_get2
    match "mobile/manager/get" => :mobile_manager_get
    match "mobile/messages/get" => :mobile_messages_get
    match "mobile/conversation/create" => :mobile_conversation_create
    match "mobile/conversations/get" => :mobile_conversations_get
    #match "mobile/manager/buying"=>:mobile_manager_buying
    #match "mobile/manager/selling"=>:mobile_manager_selling
    match "mobile/conversation/update" => :mobile_conversation_update
    match "mobile/email/signup" => :mobile_email_signup
    match "mobile/categories/all" => :mobile_categories_all
    match "mobile/alert/create" => :mobile_alert_create
    match "mobile/alert/remove" => :mobile_alert_remove
	match "mobile/alert/edit" => :mobile_alert_edit
	
    match "mobile/transaction/complete" => :mobile_transaction_complete
    match "mobile/transaction/cc" => :mobile_transaction_cc

    match "mobile/push/setup" => :mobile_push_setup
    match "mobile/push/setup/android" => :mobile_push_setup_android
    #TODO remove after testing
    match "mobile/push/send/android" => :mobile_push_send_android
    match "mobile/push/conversation/get" => :mobile_push_conversation_get

    match "mobile/posting/agree/sell" => :mobile_posting_agree_sell
    match "mobile/posting/cancel/sell" => :mobile_posting_cancel_sell

    match "mobile/payments/transact/cc" => :mobile_payments_transact_cc
    match "mobile/payments/set/seller" => :mobile_payments_set_seller
    match "mobile/payments/set/buyer" => :mobile_payments_set_buyer
    match "mobile/payments/get/cards" => :mobile_payments_get_cards
    match "mobile/payments/get/card" => :mobile_payments_get_card
    match "mobile/payments/update/card" => :mobile_payments_update_card
    match "mobile/payments/invalidate/card" => :mobile_payments_invalidate_card

    match "mobile/payments/get/bankAccounts" => :mobile_payments_get_bankAccounts
    match "mobile/payments/get/bankAccount" => :mobile_payments_get_bankAccount
    match "mobile/payments/delete/bankAccount" => :mobile_payments_delete_bankAccount

    match "mobile/browse" => :browse
    match "mobile/search" => :search
    match "mobile/listing_details_view" => :listing_details_view

    match "mobile/return_groups" => :return_groups

    match "mobile/toggle_bookmark" => :toggle_bookmark
    match "mobile/return_bookmarks" => :return_bookmarks


    match "mobile/join_group" => :join_group
    match "mobile/leave_group" => :leave_group

    match "mobile/onboarding_add_interests" => :onboarding_add_interests
    match "mobile/onboarding_add_school_email" => :onboarding_add_school_email


    match "mobile/reset_password" => :reset_password
	
	match "mobile/get_alerts"=>:get_alert_labels
	match "mobile/get_alert_postings"=>:get_alert_postings
	
	match "mobile/queue_cg"=>:queue_craigslist_post
  end


  controller :upload do
    get ":user_name/upload" => :catchGet #Not sure why; simply setting a form :url => handle_upload_url (as in fileupload/_main) will cause a get call to said URL. Catch it and return nothing to avoid an annoying (but harmless?) routing error.
    post ":user_name/upload" => :create, :as => :handle_upload
    delete ":user_name/postings/upload_destroy/:id" => :destroy, :as => :upload_destroy
  end


  scope ":user_name", :as => "user" do
    match "postings/:id/conversations" => redirect("/conversations/postings/%{id}")
    post "postings/new" => "postings#create"
    get "postings" => redirect("/%{user_name}/")
    resources :postings
  end

  controller :postings do
    match ":user_name/postings/:id/delist_posting_modal" => :load_delist_modal, :as => :load_delist_modal
    match ":user_name/postings/:id/promote_posting_modal" => :load_promote_modal, :as => :load_promote_modal
    match ":user_name/postings/:id/load_email_share_modal" => :load_email_share_modal, :as => :load_email_share_modal
    match ":user_name/postings/:id/delist_posting" => :delist_posting, :as => :delist_posting
    match ":user_name/postings/:id/relist_posting" => :relistPosting, :as => :relist_posting
    match ":user_name/postings/:id/relist_posting_copy" => :relistPostingCopy, :as => :relist_posting_copy
    match ":user_name/postings/:id/postToCraigslist" => :postToCraigslist, :as => :post_to_craigslist
    match ":user_name/postings/:id/posting_to_craigslist" => :craigslist_loading, :as => :craigslist_loading
    post ":user_name/postings/:id/craigslist_ajax" => :craigslist_ajax, :as => :craigslist_ajax
    post ":user_name/postings/:id/promote_posting_by_email" => :promote_posting_by_email, :as => :promote_posting_by_email
    match "postings/:id/remove_completed_posting" => :remove_completed_posting, :as => :remove_completed_posting
    match "get_custom_fields" => :get_custom_fields
    post 'categorize_posting' => :categorize_posting
    post 'new_posting_form_for_category' => :new_posting_form_for_category
    match 'form_data_for_bookmark' => :form_data_for_bookmark, :as => :form_data_for_bookmark
    get "all" => :all_postings
    match "post_from_bookmark" => :post_from_bookmark, :as => :post_from_bookmark

app/views/browse/_category_menu.html.erb
<div class="unstyled light-gray-gradient dropdown" id="browse-by-category-selector">
  <div class="dropdown-toggle" data-toggle="dropdown"><div id="browse-by-category">
    <span id="current-category"><%= current_category && current_category!="All" ? current_category : "Browse by Category"  %></span>&nbsp;&#9662;
  </div></div>

    <ul class="dropdown-menu">
      <li>
      <%= link_to "All Categories", search_url(params.merge(:page => 1).except(:cfv, :search_item, :category)) %>
      </li>
      <% Posting.top_level_categories.sort.each do |top_level_category|
        if Posting.is_leaf?(top_level_category) %>
              <%= render(:partial=> "browse/category_menu_leaf", :locals=>{:category=>top_level_category})%>
          <% else %>
              <%= render(:partial=> "browse/category_menu_not_leaf", :locals=>{:category=>top_level_category})%>
          <% end %>
      <% end %>
    </ul>
</div>

app/views/browse/_category_menu_leaf.html.erb
<li><%= link_to category, search_url(params.merge(:category => category, :page => 1).except(:cfv, :search_item)) %></li>

app/views/browse/_category_menu_not_leaf.html.erb
<li class="dropdown-submenu">
  <%= link_to category, search_url(params.merge(:category => category, :page => 1).except(:cfv, :search_item)) %>
  <ul class="dropdown-menu">
    <% Posting.immediate_children_of_category(category).each do |child|
      if Posting.is_leaf?(child) %>
            <%= render(:partial=> "browse/category_menu_leaf", :locals=>{:category=>child})%>
      <%else %>
            <%= render(:partial=> "browse/category_menu_not_leaf", :locals=>{:category=>child})%>
    <% end
    end %>
  </ul>
</li>

app/views/browse/_custom_field_checkboxes.html.erb
<tr><td class="custom-field-table-label"><%= drop_down_label %> &nbsp;&nbsp;</td>
  <td class="custom-field-table-checkboxes">
  <% drop_down_options.each do |option| %>
      <div style="display:inline-block;">
        <% if params.fetch(:cfv, "").include?("  #{option}  ") # give option to remove filter           %>
            <%= link_to (search_url(params.merge(:page => 1, :cfv => params[:cfv].sub("  #{option}  ", "")))) do %>
                <input type="checkbox" checked="checked"/>
            <% end %>
        <% else %>
            <%= link_to (search_url(params.merge(:page => 1, :cfv => params.fetch(:cfv, "")+"  #{option}  ", :page => 1))) do %>
                <input type="checkbox"/>
            <% end %>
        <% end %> <%= "#{option}" %>
    &nbsp;&nbsp;&nbsp;</div>
  <% end %>
  </td>
</tr>

app/views/browse/_filters.html.erb
<% if !params[:search_item].blank? || ((!params[:wd].nil?) && params[:wd]!="30") || ((!params[:pmin].nil?) && params[:pmax]) ||
        (params[:category] && params[:category]!="All") || params[:group] || params[:cfv] %>
    <div style="font-size:20px; font-weight:400; padding-top:10px;"></div>
<% end %>
<% if (!params[:wd].nil?) && params[:wd]!="30" %>
    <span class="filter-bubble"><%= link_to "&times;".html_safe, search_url(params.except(:wd)) %>&nbsp;&nbsp;within <%= params[:wd] %>
      miles of <%= params[:location] %> </span>
<% end %>
<% if (!params[:pmin].nil?) && params[:pmax] %>
    <span class="filter-bubble"><%= link_to "&times;".html_safe, search_url(params.except(:pmin, :pmax)) %>&nbsp;&nbsp;<%= number_to_currency((params[:pmin].blank? ? 0 : params[:pmin]), :precision => 0) %>
      -<%= number_to_currency((params[:pmax].blank? ? 10000000 : params[:pmax]), :precision => 0) %> </span>
<% end %>
<% number_of_ancestors=@ancestry_line.length
   @ancestry_line.each_with_index do |ancestor, index|
     parent_of_ancestor=(index==number_of_ancestors-1) ? "All" : @ancestry_line[index+1] %>
    <span class="filter-bubble">
            <%= link_to "&times;".html_safe, search_url(params.merge(:category => parent_of_ancestor, :page => 1).except(:cfv)) %>&nbsp;&nbsp;
      <%= ancestor %> </span>
<% end %>
<% if params[:category] && params[:category]!="All"
     parent=@ancestry_line[0]||= "All" %>
    <span class="filter-bubble">
            <%= link_to "&times;".html_safe, search_url(params.merge(:category => parent, :page => 1).except(:cfv)) %>&nbsp;&nbsp;
      <%= params[:category] %></span>
<% end %>
<% unless params[:search_item].blank? %>
    <div class="filter-bubble"><%= link_to "&times;".html_safe, search_url(params.except(:search_item)) %>
      &nbsp;&nbsp;"<%= params[:search_item] %>"</div>
<% end %>
<% unless @drop_down_menus.nil?
     @drop_down_menus.each_pair do |drop_down_menu_label, drop_down_menu_options|
       drop_down_menu_options.each do |option|
         if params.fetch(:cfv, "").include?("  #{option}  ") # give option to remove filter    %>
                <span class="filter-bubble"><%= link_to "&times;".html_safe, search_url(params.merge(:page => 1, :cfv => params[:cfv].sub("  #{option}  ", ""))) %>&nbsp;&nbsp;<%= option %> </span>
            <% end  end end end %>
<% if params[:group] %>
    <div class="filter-bubble"><%= link_to "&times;".html_safe, search_url(params.except(:group)) %>&nbsp;&nbsp;&nbsp;&nbsp;group: "<%= Group.find_by_id(params[:group]).long_name %>"</div>
<% end %>

app/views/browse/_grid_result.html.erb
<% seller=User.find(posting.user_id) %>
<div id="result<%= index %>" class="result-row grid-result" data-id="<%=posting.id%>">

  <div class="card-shape">
    <div class="posting_picture" data-url="<%= user_posting_url(:user_name => seller.user_name, :id => posting.id) %>">
      <%=render(:partial => "browse/posting_picture",
           :locals => {:posting => posting, :seller=> seller, :is_bookmarked=> is_bookmarked}) %>
    </div>

    <%= rep_meter_white_back(seller.repscore, "rep-score-grid-result") %>
  </div>
  <%= link_to load_mini_map_url(:id=>posting.id), :class=>"location-marker-link", :remote=>true do %>

  <div class="text-distance">
    <%= image_tag 'browse/locationicon.png' %>&nbsp;&nbsp;&nbsp;
    <%= number_with_precision(posting.sphinx_attributes['@geodist'].to_f*0.000621371, :precision => 1) %>
    miles &nbsp; <%= ::DistanceCalculations.compass_bearing(params[:latitude], params[:longitude], posting.latitude*180/Math::PI, posting.longitude*180 / Math::PI) %>
  </div>
      <% end %>
  <div class="price-tag"></div>
  <div class="text-price">
    $<%= formatted_price(posting.price) %>
  </div>
  <div class="blue-title-section">
      <%= link_to truncate(posting.title, :length => 30, :separator => "..."), user_posting_url(:user_name => seller.user_name, :id => posting.id)%>
  </div>

</div>

app/views/browse/_groups_filter.html.erb
<div class="group-filters">
  <div class="filter-title">Groups</div>
  <br>
  <div class="filter-inputs">
    <div>
      <span class="group-checkbox" id="group-checkbox0" data-url="1">&#10003;&nbsp;&nbsp; All of
      Reppio</span>
    </div>
    <% users_groups ||= []
       users_groups.each do |group| %>
        <div>
          <span class="group-checkbox" id="group-checkbox<%= group.id %>" data-url="<%= group.id %>">&#x25a2;&nbsp;&nbsp; <%= group.long_name %></span>
        </div>
    <% end %>
    <div>
      <%= link_to "... more groups", groups_url, :target => "_blank" %>
    </div>
  </div>
</div>

app/views/browse/_load_postings.html.erb
<% userBookmarks=current_user.bookmarks

   @results.each_with_index do |posting, index|
     index_within_batch=index
     index+=@per_page*(params[:page].to_i - 1)
     is_bookmarked=userBookmarks.length>0 && userBookmarks.any? { |bookmark| bookmark.posting_id==posting.id }
%>
    <%= render(:partial => "browse/#{params[:view]=="rows" ? "posting_row" : "grid_result"}",
               :locals => {:posting => posting, :index => index,
                           :is_bookmarked => is_bookmarked, :index_within_batch => index_within_batch
               }) %>

<% end %>

app/views/browse/_location_filter.html.erb
<div class="location-filters">
  <div style="margin-bottom:20px;" class="filter-title">Distance</div>
  <div class="filter-inputs">
    <div class="filter-inputs">
      <input type="text" id="within-distance" class="fill-in-the-blank" value="" placeholder="30" name="wd"/>
      miles &nbsp;&nbsp;&nbsp;&nbsp;from &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="locationField" class="fill-in-the-blank" value="" name="location"/>
      <%= image_tag('browse/locationicon2.png', :id=>"current-location-no-map", :class => 'current-location-image') %>


    </div>
  </div>
</div>

app/views/browse/_posting_picture.html.erb
<%= image_tag(posting.first_picture_url.gsub("large_thumb", "medium"), :class => "posting_picture_image")%>

<div class="posting_description">
  <%= truncate(posting.description, :length=>180, :separator=>"...") %>
  <br><br>
  <i class="icon-time"></i>&nbsp;&nbsp;<%= time_ago_in_words(posting.updated_at) %> ago
</div>

<div class="bookmark grid-bookmark">
  <% if is_bookmarked %>
      <span class="bookmarked"></span>
  <% else %>
      <span class="bookmark-this"></span>
  <% end %>
</div>


<div class="mutualfriends" data-sellername="<%= seller.first_name%>" data-sellerid="<%= seller.facebook_id %>" data-postingismine="<%= (current_user.id==seller.id) ? "true" : "false" %>"><span class="friendlist"></span></div>

<div class="seller-pic">
  <%= link_to image_tag(posting.first_user_url), seller %>
</div>

app/views/browse/_posting_row.html.erb
<% seller=User.find(posting.user_id) %>
<div id="result<%= index %>" class="result-row" data-id="<%=posting.id%>">
  <div id="<%= posting.id %>" class="result-td shadow light-gray-gradient list-td">
      <%= link_to image_tag(posting.first_picture_url.gsub("large_thumb", "medium")), user_posting_url(:user_name=>seller.user_name, :id=>posting.id), :class=>"list-item-picture shadow" %>

    <div class="list-title"><%= link_to posting.title, user_posting_url(:user_name => seller.user_name, :id => posting.id)%>
    </div>

    <div class="list-description">
      <%= posting.description %>
    </div>

    <div class="orange-price-label"></div>


    <div class="text-price list-search-price-pos">
      $<%= formatted_price(posting.price) %>
    </div>

    <div class="list-posting-and-time">
      <br><i class="icon-map-marker" style="color:#767676;"></i> <%= number_with_precision(posting.sphinx_attributes['@geodist'].to_f*0.000621371, :precision => 1) %>
      miles    <%= ::DistanceCalculations.compass_bearing(params[:latitude], params[:longitude], posting.latitude*180/Math::PI, posting.longitude*180 / Math::PI) %>
          &nbsp;&nbsp;&nbsp;&nbsp;
          <icon class="icon-time" style="color:#767676;"></icon> <%= time_ago_in_words(posting.updated_at) %>
    </div>

    <div class="bookmark bookmark-list">
      <% if is_bookmarked %>
          <span class="bookmarked"></span>
      <% else %>
          <span class="bookmark-this"></span>
      <% end %>
    </div>

    <div class="mutualfriends" data-sellerid="<%= seller.facebook_id %>" data-postingismine="<%= (current_user.id==seller.id) ? "true" : "false" %>"><span class="friendlist"></span></div>



    <div class="seller-name">
      <%= link_to seller.first_name, seller %>
    </div>


    <div class="seller-pic">
      <%= link_to image_tag(posting.first_user_url), seller %>
    </div>

    <%= rep_meter_small(seller.repscore, "rep-score-posting-row-search") %>
  </div>
</div>

app/views/browse/map_markers.js.erb
bounds = new google.maps.LatLngBounds();
bounds.extend(centerPoint);
<% if params[:page].to_i==1 #clear all existing markers if from pjax call %>
if (markers.length !== 0) {
    for (var i = 0; i < markers.length; ++i) {
        markers[i].setMap(null);
    }
}
markers = [];
<% end

   @results.each_with_index do |posting, index|
     index+=@per_page*(params[:page].to_i - 1)
%>

latLng = new google.maps.LatLng(<%= ::DistanceCalculations.calculateOffset(posting.latitude*180/Math::PI, posting.longitude*180 / Math::PI, 200)%>);

var marker<%= index %> = new google.maps.Marker({
    position:latLng,
    map:map,
    icon:rep_marker,
    animation:google.maps.Animation.DROP,
    title:'<%= posting.title.gsub(/[^0-9A-Za-z ]/, '') %>',
    zIndex:1
});
markers.push(marker<%= index %>)

bounds.extend(latLng);

<% end %>



<% if params[:cl]%>

current_location_marker_shown = true;
$('.current-location-image').attr('src', "<%= asset_path "browse/current-location-on.png" %>");

var current_location_marker = new google.maps.Marker({
    clickable:false,
    icon:"<%= asset_path("browse/current_location.png")%>",
    shadow:null,
    zIndex:999,
    map:map,
    position:centerPoint
});



<% else %>
current_location_marker_shown = false;
<% end %>

if (get_url_parameter_value("search_within_map")) {
    bounds= new google.maps.LatLngBounds(new google.maps.LatLng(get_url_parameter_value("south_west").split(",")[0], get_url_parameter_value("south_west").split(",")[1]),
            new google.maps.LatLng(get_url_parameter_value("north_east").split(",")[0], get_url_parameter_value("north_east").split(",")[1]));
}

map.fitBounds(bounds);